In [48]:
import numpy as np

In [49]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

In [51]:
np.average(english_score)

67.16666666666667

In [54]:
np.max(english_score)

89

In [55]:
np.min(english_score)

48

In [60]:
np.std(english_score)

13.433995020924426

In [58]:
np.nanmean(math_score)

66.6

In [59]:
np.nanmax(math_score)

85.0

In [61]:
np.nanmin(math_score)

60.0

In [62]:
np.nanstd(math_score)

9.707728879609279

In [63]:
np.mean(chinese_score)

75.33333333333333

In [64]:
np.max(chinese_score)

90

In [65]:
np.min(chinese_score)

65

In [66]:
np.std(chinese_score)

8.825468196582484

In [79]:
plus_math_score=np.where(np.nan_to_num(math_score)==0,55,np.array(math_score))

In [80]:
plus_math_score

array([60., 85., 60., 68., 55., 60.])

In [82]:
print (np.mean(plus_math_score),np.max(plus_math_score),np.min(plus_math_score),np.std(plus_math_score))

64.66666666666667 85.0 55.0 9.860132971832694


In [84]:
math=np.corrcoef(chinese_score,plus_math_score)

In [85]:
english=np.corrcoef(chinese_score,english_score)

In [89]:
math

array([[1.        , 0.74056803],
       [0.74056803, 1.        ]])

In [90]:
english

array([[1.        , 0.97792828],
       [0.97792828, 1.        ]])

In [88]:
np.greater(math,english)

array([[False, False],
       [False, False]])

In [91]:
print("english")

english
