In [1]:
import numpy as np

In [7]:
array1=np.array([[10,8],[3,5]])

In [12]:
'反矩陣'
bkw_array1=np.linalg.inv(array1)
bkw_array1

array([[ 0.19230769, -0.30769231],
       [-0.11538462,  0.38461538]])

In [13]:
'單位矩陣'
new_array1=array1@bkw_array1
new_array1

array([[1., 0.],
       [0., 1.]])

In [17]:
'特徵值eigenvalue'
w,v=np.linalg.eig(new_array1)
w

array([1., 1.])

In [18]:
'特徵向量eigenvector'
v

array([[1., 0.],
       [0., 1.]])

In [19]:
'SVD'
'singular value decomposition'
'call rank'
np.linalg.matrix_rank(new_array1)

2