In [4]:
import numpy as np

In [12]:
np.__version__

'1.19.2'

In [33]:
ans_1=np.arange(0,21,1)

In [34]:
ans_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [38]:
ans_2=ans_1[0:21:2]

In [39]:
ans_2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [40]:
ans_3=ans_1[0:21:3]

In [41]:
ans_3

array([ 0,  3,  6,  9, 12, 15, 18])