In [26]:
import numpy as np

In [27]:
array1=np.array(range(30))

In [28]:
array2=np.array([2,3,5])

In [29]:
with open('multi_array.npz','wb') as f:
    np.savez(f,array1,array2)

In [30]:
npzfile=np.load('multi_array.npz')

In [31]:
type(npzfile)

numpy.lib.npyio.NpzFile

In [32]:
npzfile.files

['arr_0', 'arr_1']

In [33]:
print(npzfile['arr_0'])
print(npzfile['arr_1'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]


In [34]:
with open('new_multi_array.npz','wb') as f:
    np.savez(f,array1,array2,npzfile['arr_0'],npzfile['arr_1'])

In [35]:
new_npzfile=np.load('new_multi_array.npz')

In [36]:
new_npzfile.files

['arr_0', 'arr_1', 'arr_2', 'arr_3']

In [38]:
print(new_npzfile['arr_0'])
print(new_npzfile['arr_1'])
print(new_npzfile['arr_2'])
print(new_npzfile['arr_3'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
